### ISSUE TITLE
line 39: missmatch audio-hal path

### ISSUE THREAD

**Issue by xyzuan** [raiyanbinmohsin/device_xiaomi_sdm660-common_caf#1]
**Issue :** 
`vendor/qcom/opensource/audio-hal/primary-ha`
**It should be :P**
`vendor/qcom/opensource/audio-hal/primary-hal`

https://github.com/raiyanbinmohsin/device_xiaomi_sdm660-common_caf/blob/d0610c113f2443d2454acd886ea8c1cf0a5482bc/sdm660.mk#L39

**Comment by raiyanbinmohsin** [comment]
Thanks, sir. Let me fix it
